NAME := switches

genie_ota_config = 1
genie_time_config = 0
#if genie_lpm_config = 1 means than support low power mode
genie_lpm_config = 1

#support genie ultra provision function
genie_ultra_prov_config = 0

$(NAME)_COMPONENTS  += genie_service bluetooth.bt_host bluetooth.bt_mesh yloop cli

$(NAME)_INCLUDES += ../../../../genie_service ../../../../genie_service/sal/inc

$(NAME)_SOURCES  := switches.c switches_input.c switches_queue.c switches_output.c

# Mesh function select
GLOBAL_DEFINES += CONFIG_BT_MESH
GLOBAL_DEFINES += CONFIG_BT_MESH_PROV
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_ADV
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_GATT
GLOBAL_DEFINES += CONFIG_BT_MESH_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_GATT_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_RELAY
#GLOBAL_DEFINES += CONFIG_BT_MESH_FRIEND
#GLOBAL_DEFINES += CONFIG_BT_MESH_LOW_POWER
#GLOBAL_DEFINES += CONFIG_BT_MESH_SHELL

# Mesh foundation model select
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_HEALTH_SRV
MESH_MODEL_GEN_ONOFF_SRV = 1

#enable debug log
CONFIG_DEBUG_MODE = 1

#enable use gpio uart for debug log print
GENIE_GPIO_UART = 1

#both GENIE_MESH_AT_CMD and GENIE_MESH_BINARY_CMD should select one
#enable AT command default
GENIE_MESH_AT_CMD = 1

#enable binary command
#GENIE_MESH_BINARY_CMD = 1

#enable GLP mode for low power
GENIE_MESH_GLP = 1

#enable no auto reply by mesh module
#GENIE_MESH_NO_AUTO_REPLY = 1

GLOBAL_DEFINES += CONFIG_BT_DEVICE_NAME=\"switches\"

GLOBAL_DEFINES += PROJECT_SW_VERSION=0x00010000
GLOBAL_DEFINES += PROJECT_SECRET_KEY=\"00112233445566770011223344556677\"

GLOBAL_DEFINES += CONFIG_BT_RX_BUF_LEN=143
GLOBAL_DEFINES += CONFIG_BT_L2CAP_TX_MTU=135
GLOBAL_DEFINES += CONFIG_AIS_TOTAL_FRAME=6
GLOBAL_DEFINES += CONFIG_BT_RX_BUF_COUNT=4

#Config for low power +++++
GLOBAL_DEFINES += GENIE_DEFAULT_DURATION=205
GLOBAL_DEFINES += CONFIG_ADV_SCAN_INTERVAL_TIMER=1
GLOBAL_DEFINES += CONFIG_ADV_INTERVAL_TIMER=20
#GLOBAL_DEFINES += CONFIG_SCAN_DURATION_AFTER_GENIE_MODEL_SEND=300
GLOBAL_DEFINES += CONFIG_MESH_SCAN_INTERVAL=0x10
GLOBAL_DEFINES += CONFIG_MESH_SCAN_WINDOW=0x10
#Config for low power -----

CONFIG_DEBUG_MODE = 1

ifeq ($(CONFIG_DEBUG_MODE),1)
############### debug ###############
## BLE debug log general control macro (Note: still to be affected by DEBUG)
## Enable below macros if BLE stack debug needed
GLOBAL_DEFINES += USE_BT_MESH_CUSTOM_ERR_LOG
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_LOG
GLOBAL_DEFINES += CONFIG_BT_DEBUG

# Mesh debug message enable
#GLOBAL_DEFINES += USE_BT_MESH_CUSTOM_LOG

#GLOBAL_DEFINES += GENIE_DEBUG_COLOR
#GLOBAL_DEFINES += MESH_DEBUG_RX
#GLOBAL_DEFINES += MESH_DEBUG_TX
#GLOBAL_DEFINES += MESH_DEBUG_PROV
#GLOBAL_DEFINES += CONFIG_INIT_STACKS
#GLOBAL_DEFINES += CONFIG_PRINTK

## BLE subsystem debug log control macro
## Enable below macros if component-specific debug needed
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_L2CAP
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_CONN
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_ATT
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_GATT
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_HCI_DRIVER
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_HCI_CORE
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_CORE
#GLOBAL_DEFINES += CONFIG_BT_DEBUG_MULTI_ADV

## MESH debug log control macro
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_ADV
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_BEACON
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_PROXY
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_PROV
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_NET
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_CRYPTO
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_TRANS
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_FRIEND
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_LOW_POWER
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_ACCESS
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_FLASH
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_MODEL
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_VENDOR_MODEL
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_FACTORY
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_OTA
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_GLP
else
GLOBAL_DEFINES += CONFIG_INFO_DISABLE
endif
